export const GET_POKEMON_LIST_REQUEST = 'GET_POKEMON_LIST_REQUEST';
export const GET_POKEMON_LIST_SUCCESS = 'GET_POKEMON_LIST_SUCCESS';
export const GET_POKEMON_LIST_FAILURE = 'GET_POKEMON_LIST_FAILURE';
